// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bets.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const betExistsByIdempotencyKey = `-- name: BetExistsByIdempotencyKey :one
SELECT EXISTS(SELECT 1 FROM bets WHERE idempotency_key = $1)
`

func (q *Queries) BetExistsByIdempotencyKey(ctx context.Context, idempotencyKey string) (bool, error) {
	row := q.db.QueryRow(ctx, betExistsByIdempotencyKey, idempotencyKey)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createBet = `-- name: CreateBet :one
INSERT INTO bets (client_id, predicted_value, stake, idempotency_key, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, client_id, predicted_value, stake, status, created_at, idempotency_key
`

type CreateBetParams struct {
	ClientID       int64
	PredictedValue int32
	Stake          decimal.Decimal
	IdempotencyKey string
	Status         string
}

func (q *Queries) CreateBet(ctx context.Context, arg CreateBetParams) (Bet, error) {
	row := q.db.QueryRow(ctx, createBet,
		arg.ClientID,
		arg.PredictedValue,
		arg.Stake,
		arg.IdempotencyKey,
		arg.Status,
	)
	var i Bet
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.PredictedValue,
		&i.Stake,
		&i.Status,
		&i.CreatedAt,
		&i.IdempotencyKey,
	)
	return i, err
}

const createDraw = `-- name: CreateDraw :one
INSERT INTO draws (bet_id, die_one, die_two, die_three, product_value)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, bet_id, die_one, die_two, die_three, product_value
`

type CreateDrawParams struct {
	BetID        int64
	DieOne       int32
	DieTwo       int32
	DieThree     int32
	ProductValue int32
}

func (q *Queries) CreateDraw(ctx context.Context, arg CreateDrawParams) (Draw, error) {
	row := q.db.QueryRow(ctx, createDraw,
		arg.BetID,
		arg.DieOne,
		arg.DieTwo,
		arg.DieThree,
		arg.ProductValue,
	)
	var i Draw
	err := row.Scan(
		&i.ID,
		&i.BetID,
		&i.DieOne,
		&i.DieTwo,
		&i.DieThree,
		&i.ProductValue,
	)
	return i, err
}

const listBetHistory = `-- name: ListBetHistory :many
SELECT b.id, b.predicted_value, b.stake, b.status, b.created_at,
       d.die_one, d.die_two, d.die_three, d.product_value
FROM bets b
         JOIN draws d ON d.bet_id = b.id
WHERE b.client_id = $1
ORDER BY b.created_at DESC
LIMIT $2
`

type ListBetHistoryParams struct {
	ClientID int64
	Limit    int32
}

type ListBetHistoryRow struct {
	ID             int64
	PredictedValue int32
	Stake          decimal.Decimal
	Status         string
	CreatedAt      time.Time
	DieOne         int32
	DieTwo         int32
	DieThree       int32
	ProductValue   int32
}

func (q *Queries) ListBetHistory(ctx context.Context, arg ListBetHistoryParams) ([]ListBetHistoryRow, error) {
	rows, err := q.db.Query(ctx, listBetHistory, arg.ClientID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBetHistoryRow
	for rows.Next() {
		var i ListBetHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.PredictedValue,
			&i.Stake,
			&i.Status,
			&i.CreatedAt,
			&i.DieOne,
			&i.DieTwo,
			&i.DieThree,
			&i.ProductValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
