// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package db

import (
	"context"

	"github.com/shopspring/decimal"
)

const clientExists = `-- name: ClientExists :one
SELECT EXISTS(SELECT 1 FROM clients WHERE id = $1)
`

func (q *Queries) ClientExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, clientExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countClients = `-- name: CountClients :one
SELECT COUNT(*) FROM clients
`

func (q *Queries) CountClients(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countClients)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (username, balance) VALUES ($1, $2) RETURNING id, username, balance, created_at
`

type CreateClientParams struct {
	Username string
	Balance  decimal.Decimal
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (Client, error) {
	row := q.db.QueryRow(ctx, createClient, arg.Username, arg.Balance)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getClient = `-- name: GetClient :one
SELECT id, username, balance, created_at FROM clients WHERE id = $1
`

func (q *Queries) GetClient(ctx context.Context, id int64) (Client, error) {
	row := q.db.QueryRow(ctx, getClient, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getClientForUpdate = `-- name: GetClientForUpdate :one
SELECT id, username, balance, created_at FROM clients WHERE id = $1 FOR UPDATE
`

// Pessimistic lock, mirroring ClientRepository.findByIdForUpdate:
// prevents concurrent transactions from reading a stale balance.
func (q *Queries) GetClientForUpdate(ctx context.Context, id int64) (Client, error) {
	row := q.db.QueryRow(ctx, getClientForUpdate, id)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const updateClientBalance = `-- name: UpdateClientBalance :exec
UPDATE clients SET balance = $2 WHERE id = $1
`

type UpdateClientBalanceParams struct {
	ID      int64
	Balance decimal.Decimal
}

func (q *Queries) UpdateClientBalance(ctx context.Context, arg UpdateClientBalanceParams) error {
	_, err := q.db.Exec(ctx, updateClientBalance, arg.ID, arg.Balance)
	return err
}
