// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/shopspring/decimal"
)

type Bet struct {
	ID             int64
	ClientID       int64
	PredictedValue int32
	Stake          decimal.Decimal
	Status         string
	CreatedAt      time.Time
	IdempotencyKey string
}

type Client struct {
	ID        int64
	Username  string
	Balance   decimal.Decimal
	CreatedAt time.Time
}

type Draw struct {
	ID           int64
	BetID        int64
	DieOne       int32
	DieTwo       int32
	DieThree     int32
	ProductValue int32
}

type Transaction struct {
	ID           int64
	BetID        int64
	ClientID     int64
	Type         string
	Amount       decimal.Decimal
	BalanceAfter decimal.Decimal
	CreatedAt    time.Time
}
