// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (bet_id, client_id, type, amount, balance_after)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, bet_id, client_id, type, amount, balance_after, created_at
`

type CreateTransactionParams struct {
	BetID        int64
	ClientID     int64
	Type         string
	Amount       decimal.Decimal
	BalanceAfter decimal.Decimal
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.BetID,
		arg.ClientID,
		arg.Type,
		arg.Amount,
		arg.BalanceAfter,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.BetID,
		&i.ClientID,
		&i.Type,
		&i.Amount,
		&i.BalanceAfter,
		&i.CreatedAt,
	)
	return i, err
}

const listTransactionHistory = `-- name: ListTransactionHistory :many
SELECT id, bet_id, type, amount, balance_after, created_at
FROM transactions
WHERE client_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListTransactionHistoryParams struct {
	ClientID int64
	Limit    int32
}

type ListTransactionHistoryRow struct {
	ID           int64
	BetID        int64
	Type         string
	Amount       decimal.Decimal
	BalanceAfter decimal.Decimal
	CreatedAt    time.Time
}

func (q *Queries) ListTransactionHistory(ctx context.Context, arg ListTransactionHistoryParams) ([]ListTransactionHistoryRow, error) {
	rows, err := q.db.Query(ctx, listTransactionHistory, arg.ClientID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransactionHistoryRow
	for rows.Next() {
		var i ListTransactionHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.BetID,
			&i.Type,
			&i.Amount,
			&i.BalanceAfter,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
