services:
  postgres:
    image: postgres:16-alpine
    container_name: threedice-db
    environment:
      POSTGRES_DB: threedice
      POSTGRES_USER: threedice
      POSTGRES_PASSWORD: threedice
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
