[phases.setup]
nixPkgs = ["jdk21", "maven"]

[phases.build]
cmds = [
	"java -version",
	"javac -version",
	"mvn -v",
	"JAVA_HOME=$(dirname $(dirname $(readlink -f $(which javac)))) mvn -B -DskipTests clean package"
]

[start]
cmd = "java -jar target/*.jar"
